services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "your_bot_token_here"
      - key: WEBHOOK_URL
        value: "your_webhook_url_here"
      - key: MONGO_URL
        value: "your_mongo_url_here"
      - key: ADMIN_ID
        value: "your_admin_id_here"
