services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "your-bot-token-here"  # Replace this in the Render dashboard
      - key: MONGO_URL
        value: "your-mongo-url-here"  # Replace this in the Render dashboard
      - key: ADMIN_ID
        value: "your-admin-id-here"  # Replace this in the Render dashboard
      - key: WEBHOOK_URL
        value: "your-webhook-url-here"  # Replace this in the Render dashboard
